name: Build  hugo  and  deploy 

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.124.1' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Get Theme
        run: git submodule update --init --recursive
        
      - name: Update theme to Latest commit
        run: git submodule update --remote --merge
        
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          
      - name: Build with Hugo
        run: |
          hugo \
            --buildDrafts --gc 
      - name: Echo ENV 
        run: echo "${{ secrets.DELPY_KEY }}"
      - name: DeployToAliyun
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./public
          remote_path: /home/admin/zhangwb/public # 需要先手动在远程主机创建该目录，否则会执行失败
          remote_host: ${{ secrets.DELPY_HOST }} # 远程主机 IP
          remote_port: 22  # ssh 端口，默认为 22
          remote_user: ${{ secrets.DELPY_USER }} # ssh user
          remote_key: ${{ secrets.DELPY_KEY }} # ssh 私钥
