name: Build  hugo  and  deploy 

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: ${{ github.event.inputs.hugoVersion || '0.124.1' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Get Theme
        run: git submodule update --init --recursive
        
      - name: Update theme to Latest commit
        run: git submodule update --remote --merge
        
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          
      - name: Build with Hugo
        run: |
          hugo \
            --buildDrafts --gc 
      - name: Echo ENV 
        run: echo "${{ secrets.DELPY_KEY }}"
      - name: DeployToAliyun
        uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
        env:
          DEPLOY_KEY: ${{ secrets.DELPY_KEY }} # 引用配置，SSH私钥
          ARGS: -avz --delete  
          SERVER_PORT: "22" # SSH端口
          FOLDER: ./public # 要推送的文件夹，路径相对于代码仓库的根目录，视情况替换为自己的文件夹路径
          SERVER_IP: ${{ secrets.DELPY_HOST }} # 引用配置，服务器的host名（IP或者域名domain.com）
          USERNAME: admin # 引用配置，服务器登录名
          SERVER_DESTINATION: /home/admin/zhangwb/public  # 部署到目标文件夹
